### ISSUE TITLE
Deploy: Add a Gitpod deployment docker-compose based setup

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/devops#1]
Docker Compose @singhalkarun 
- [x] AI Tools
- [x] BFF
- [x] Transport Socket
- [x] Gitpod to be updated for Transport Socket and Frontend
- [x] How to securely share a .env file for ai-tools and bff.
- [ ] Update the code to pick up env variable from `process.env` =>`configservice` @Amruth-Vamshi 

Setup frontend (for contribution)
- [x] Shell file to setup frontend @geeky-abhishek  PR- https://github.com/AmakrushAI/app/pull/62

**Comment by singhalkarun** [comment]
@ChakshuGautam https://github.com/gitpod-io/gitpod/issues/4456#issuecomment-994953171

GitPod provides way to define project level environment variables for private repos which are available during pre-builds as well as workspaces. We can disable their availability in workspaces.

![Image](https://user-images.githubusercontent.com/113603846/232469899-5584f78e-e88b-490a-84a5-a86059c2fd2f.png)
